### ISSUE TITLE
[Bug]: wait_for_ssh_connectivity() method is failing with command execution error

### ISSUE THREAD

**Issue by mashetty330** [red-hat-storage/ocs-ci#12972]
### Description
wait_for_ssh_connectivity() method in VM class is throwing the below error every time its called:

```
2025-08-14 20:09:02,783 - MainThread - INFO - ocs_ci.ocs.cnv.virtual_machine.wait_for_ssh_connectivity.409 - Waiting for the SSH connectivity to establish to vm-test-bc4bba5ca8b34689bc225fa2c7efd2c1 
2025-08-14 20:09:02,783 - MainThread - INFO - ocs_ci.ocs.cnv.virtual_machine.run_ssh_cmd.610 - Executing exit command on the vm-test-bc4bba5ca8b34689bc225fa2c7efd2c1 VM using SSH
2025-08-14 20:09:02,783 - MainThread - INFO - ocs_ci.helpers.cnv_helpers.get_ssh_pub_key_with_filename.40 - Retrieving the content and file name of the SSH public key from the client machine
2025-08-14 20:09:02,783 - MainThread - INFO - ocs_ci.helpers.cnv_helpers.get_ssh_pub_key_with_filename.61 - Using ssh key from ocs-ci default config: ~/.ssh/openshift-dev.pub
2025-08-14 20:09:02,784 - MainThread - INFO - ocs_ci.helpers.cnv_helpers.get_ssh_private_key_path.315 - The private key used for authenticating to the server: /home/jenkins/.ssh/openshift-dev.pem
2025-08-14 20:09:02,784 - MainThread - INFO - ocs_ci.utility.utils.exec_cmd.690 - Executing command: virtctl --namespace namespace-vm-fd60cd7d9c54453aab2103586d8 ssh vm-test-bc4bba5ca8b34689bc225fa2c7efd2c1 '--local-ssh-opts=-o StrictHostKeyChecking=no' --username=admin --identity-file=/home/jenkins/.ssh/openshift-dev.pem --port=22 -c exit
2025-08-14 20:09:02,832 - MainThread - DEBUG - ocs_ci.utility.utils.exec_cmd.709 - Command stdout is empty
2025-08-14 20:09:02,832 - MainThread - WARNING - ocs_ci.utility.utils.exec_cmd.714 - Command stderr: target must contain type and name separated by '/'
```

### Steps to Reproduce
1. Create VM workload using cnv_workload() fixture
2.
3.

### Environment
- Test Suite(s):
- Platform(s):
- Version(s):
- OS:

### Additional Context

Run: https://url.corp.redhat.com/f5f8d9e

**Comment by PrasadDesala** [comment]
@avd-sagare could you please look into it?

**Comment by avd-sagare** [comment]
This issue has been addressed as part of a recently merged pull request. 
 https://github.com/red-hat-storage/ocs-ci/pull/11088/files#diffb155ed90527e24a4c97de81cfb916eb5de47cbc2dfa09bbc254025b5fe9c9c6fR224

**Comment by mashetty330** [comment]
Issue is not resolved. Tests are failing for the same reason: https://url.corp.redhat.com/a15cff4

**Comment by Akarsha-rai** [comment]
The issue requires reopening as failures persist in the 4.18 branch, the necessary changes might need to be pushed to release-4.18.

**Comment by PrasadDesala** [comment]
the issue has been backported to 4.18
