### ISSUE TITLE
Issues from the OCS-CI Gaps document 

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#3641]
Some of the issues are, we can create a new sub-issue or use this as master list to strikedown sub-issue

- It does not make sense for me to replace my sed tool (or any other tool) with gnu-sed in PATH. I will suggest to just use gnu-sed inside the ci scripts instead
 

-  Unabling to deploy/teardown a cluster creates a problem when we are trying to contribute deployment/teardown code, we need to find a way to enable us to test these code paths an not wait for a verification job run to find bugs 

- It is not very easy to run the test suite(s) locally, aka trigger them locally or somewhere to run against some setup of openshift, with your own builds. 

> This is probably somehting that user is missing on how to setup locally and run,  It is quite easy to run locally, cluster setup is something different from running ocs-ci, those reqiurements have to be met by operator installer

- the need for the pull secret but the docs didn't make clear which of the other keys were required and where to get them, My ideal for the "Getting Started" doc is that it be more of a "one stop shop" for someone who simply wants to do a basic run of the tool.  

- There are many options in the YAML config that are unclear to me and many of the options are not documented inline. The subsections for "RUN", "DEPLOYMENT", and "ENV_DATA" are unclear and I wouldn't know what section to look for a particular option in 

- as a design point I think that module import should not trigger complex code or use resources outside of the python source files themselves. If network resources are needed to create decorators, they should be deferred until the function itself is going to run

- Fixtures should be reserved for resources that have an external dependency such as a persistent network connection, database, etc. or complex/expensive data structure. Even then I recommend the fixture be a minimal wrapper around library functions whenever possible

-  I would recommend the use of a tool such as "black". Many in the Python community now use "black" to unify style and avoid having to make developers pep8 conscious.

> Fixed by issue: https://github.com/red-hat-storage/ocs-ci/issues/2952

**Comment by clacroix12** [comment]
> It does not make sense for me to replace my sed tool (or any other tool) with gnu-sed in PATH. I will suggest to just use gnu-sed inside the ci scripts instead

We don't control the scripts that are calling `sed` directly which is why I opted to have mac users deploying UPI configure a `sed` that is compatible with the scripts.

> There are many options in the YAML config that are unclear to me and many of the options are not documented inline. The subsections for "RUN", "DEPLOYMENT", and "ENV_DATA" are unclear and I wouldn't know what section to look for a particular option in

We have addressed this point with much more extensive [documentation](https://github.com/red-hat-storage/ocs-ci/blob/master/conf/README.md) around the configuration.

> the need for the pull secret but the docs didn't make clear which of the other keys were required and where to get them, My ideal for the "Getting Started" doc is that it be more of a "one stop shop" for someone who simply wants to do a basic run of the tool.

The pull secret isn't our requirement but an openshift one, I'm not sure how we get around this from the user setup perspective. If we went with a containerized dev environment sure but that also has several other factors to consider before we would go that route. I think all we can do is make it clear that users will need the pull secret (and other files that contain sensitive authentication data like auth.yaml) and provide a relatively easy way for them to request it.

**Comment by ebenahar** [comment]
Re-opening as some of the aforementioned issues still persist
