### ISSUE TITLE
test_rgw_host_node_failure intermittently fails in our OCS-CI runs, and demands further inspection

### ISSUE THREAD

**Issue by bernerhat** [red-hat-storage/ocs-ci#3926]
See title

**Comment by ebenahar** [comment]
Hi @Akarsha-rai could you please have a look?

**Comment by ebenahar** [comment]
@parikshithb @PrasadDesala could you please have a look too?

**Comment by Akarsha-rai** [comment]
When a hosted node is down `noobaa-db` pod remains in a `Terminating` state which results in OBC creation failure. 
Once the node and db pod up creating OBC should fix the issue.

**Comment by MeridianExplorer** [comment]
The issue persists/has returned, as can be seen in runs 1631876216, 1630836070, 1631234507, and a few more
